{% set name = "frogress" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da5b8206bce00ae245002975f50b73362e5d2e81151b48c66cfd4b15ba28952c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - __unix

test:
  imports:
    - frogress
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/lukaszb/frogress
  summary: 'frogress - a progress tool for shell'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
